spring.datasource.url: jdbc:mysql://localhost:3306/devpub?useUnicode=true&characterEncoding=utf8
spring.datasource.username: root
spring.datasource.password: Java2020
spring.jpa.generate-ddl: false
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: validate

title: DevPub
subtitle: Рассказы разработчиков
phone: +7 906 888-90-62
email: e.galimsarov@gmail.com
copyright: Евгений Галимсаров
copyrightFrom: 2020