INSERT INTO `tags` (`id`,`name`) VALUES (2,'*nix');
INSERT INTO `tags` (`id`,`name`) VALUES (28,'.NET');
INSERT INTO `tags` (`id`,`name`) VALUES (17,'Cognitive Pilot');
INSERT INTO `tags` (`id`,`name`) VALUES (8,'IT-компании');
INSERT INTO `tags` (`id`,`name`) VALUES (27,'IT-эммиграция');
INSERT INTO `tags` (`id`,`name`) VALUES (25,'Nginx');
INSERT INTO `tags` (`id`,`name`) VALUES (16,'Open source');
INSERT INTO `tags` (`id`,`name`) VALUES (13,'Биотехнологии');
INSERT INTO `tags` (`id`,`name`) VALUES (11,'Визуализация данных');
INSERT INTO `tags` (`id`,`name`) VALUES (22,'Высокая производительность');
INSERT INTO `tags` (`id`,`name`) VALUES (9,'Законодательство в IT');
INSERT INTO `tags` (`id`,`name`) VALUES (14,'Здоровье');
INSERT INTO `tags` (`id`,`name`) VALUES (1,'Информационная безопасность');
INSERT INTO `tags` (`id`,`name`) VALUES (7,'Карьера в IT-индустрии');
INSERT INTO `tags` (`id`,`name`) VALUES (12,'Научно-популярное');
INSERT INTO `tags` (`id`,`name`) VALUES (18,'Обработка изображений');
INSERT INTO `tags` (`id`,`name`) VALUES (21,'Онтико');
INSERT INTO `tags` (`id`,`name`) VALUES (10,'Открытые данные');
INSERT INTO `tags` (`id`,`name`) VALUES (4,'Программирование');
INSERT INTO `tags` (`id`,`name`) VALUES (23,'Разработка веб-сайтов');
INSERT INTO `tags` (`id`,`name`) VALUES (5,'Реверс-инжиниринг');
INSERT INTO `tags` (`id`,`name`) VALUES (20,'Робототехника');
INSERT INTO `tags` (`id`,`name`) VALUES (3,'Серверное администрирование');
INSERT INTO `tags` (`id`,`name`) VALUES (24,'Софт');
INSERT INTO `tags` (`id`,`name`) VALUES (6,'Управление персоналом');
INSERT INTO `tags` (`id`,`name`) VALUES (26,'Управление продуктом');
INSERT INTO `tags` (`id`,`name`) VALUES (19,'Управление проектами');
INSERT INTO `tags` (`id`,`name`) VALUES (29,'Читальный зал');
INSERT INTO `tags` (`id`,`name`) VALUES (15,'Яндекс');
